
-- GROUP BY

--Find the total number of cars sold by each showroom.
SELECT Showroom.ShowroomName, count(CarInventory.StockStatus) as StockSold
from Showroom
join CarInventory
on Showroom.ShowroomID=CarInventory.ShowroomID
group by Showroom.ShowroomID,Showroom.ShowroomName

--Display total sales amount generated by each car brand.
select Brand.BrandName ,sum(sales.SalePrice) as TotalSales
from Brand
join Sales
on Brand.BrandID=Sales.BrandID
group by Brand.BrandName,Brand.BrandID


--HAVING

--List sales executives whose total sales value exceeds ₹1 crore.

select SalesExecutive.FullName,sum(Sales.SalePrice) as TotalSales
from SalesExecutive
join Sales
on SalesExecutive.ExecutiveID=Sales.ExecutiveID
group by SalesExecutive.FullName,SalesExecutive.ExecutiveID
having sum(Sales.SalePrice)>10000000